apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-tool
  labels:
    app: ip-tool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ip-tool
  template:
    metadata:
      labels:
        app: ip-tool
    spec:
      volumes:
        - name: output-volume
          persistentVolumeClaim:
            claimName: ip-tool-pvc
      containers:
        - name: ip-tool-container
          image: ip-tool-container:latest
          volumeMounts:
            - mountPath: /output
              name: output-volume
          command: ["/bin/sh", "-c"]
          args:
            - kubectl get pod -A -o json | jq -r '.items[].status.podIP' | tee /output/ipcsv.csv &&
              python /app/ip-tool.py
